# permissions for end users to edit clustergroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clustergroup-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: global-accelerator-operator
    app.kubernetes.io/part-of: global-accelerator-operator
    app.kubernetes.io/managed-by: kustomize
  name: clustergroup-editor-role
rules:
- apiGroups:
  - infrastructure.wildlife.io
  resources:
  - clustergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.wildlife.io
  resources:
  - clustergroups/status
  verbs:
  - get
