# permissions for end users to view endpointgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: endpointgroup-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: global-accelerator-operator
    app.kubernetes.io/part-of: global-accelerator-operator
    app.kubernetes.io/managed-by: kustomize
  name: endpointgroup-viewer-role
rules:
- apiGroups:
  - globalaccelerator.aws.wildlife.io
  resources:
  - endpointgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - globalaccelerator.aws.wildlife.io
  resources:
  - endpointgroups/status
  verbs:
  - get
