apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: global-accelerator-operator
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
